version: "3.7"
services: 
  nginx:
      build:
          context: ./nginx
          dockerfile: dockerfile
      volumes: 
        - ./nginx:/var/www/html
      ports:
        - 9000:80
      tty: true 
  node:
    build: 
      context: ./node
      dockerfile: dockerfile
    volumes: 
      - ./node:/servar
    ports: 
      - 5000:5000
    tty: true
  